openapi: 3.0.1
info:
  title: Sagacious Eye for Polyp
  description: ''
  version: 1.1.0
tags:
  - name: User
  - name: Security
  - name: Record
  - name: Feature
paths:
  /users/account:
    get:
      summary: 获取用户账户信息
      deprecated: false
      description: 通过用户ID获取用户账户信息
      tags:
        - User
      parameters:
        - name: Authorization
          in: header
          description: 用户验证身份的令牌
          required: true
          example: Bearer jdaidsihsdsahjkchsjkhdkash
          schema:
            type: string
        - name: X-Csrf-Token
          in: header
          description: CSRF防护
          required: true
          example: wadsadwada
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                  userInfo:
                    $ref: '#/components/schemas/UserInfo'
                    title: 用户信息
                    description: 信息
                required:
                  - success_message
                  - userInfo
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 获取用户信息成功
                    userInfo:
                      UserName: XgOmk5
                      UserEmail: k.ucrzy@baiemdqf.kh
                      UserNickName: oRO]i
                      UserIsAdmin: true
        '404':
          description: 记录不存在
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 用户不存在
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息，用中文表示
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 获取用户信息失败
                '2':
                  summary: 异常示例
                  value:
                    error_message: CSRF Token 获取失败
      security: []
    post:
      summary: 注册用户账户
      deprecated: false
      description: >-
        创建一个新的用户账户，要求用户名全为大小写字母和数字，长度为6-20，密码长度在6-20，昵称长度在1-20，一个用户名只能用一次，一个邮箱只能注册一次。

        如果是一个管理员用户，请给我user-admin-secret如果不是，不要发送这个字段
      tags:
        - User
      parameters:
        - name: X-Csrf-Token
          in: header
          description: ''
          required: true
          example: XUYqSvTDLcFwrQvhMZrEIKtaieKrcXgn
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                user-name:
                  description: 用户名
                  example: orange
                  type: string
                user-password:
                  description: 用户密码，密码判断在前端做
                  example: bsbflsgxh..
                  type: string
                user-email:
                  description: 用户邮箱
                  example: Jin0714@outlook.com
                  type: string
                user-nickname:
                  description: 用户昵称
                  example: 晋晨曦
                  type: string
                user-admin-secret:
                  description: 管理员密码
                  example: sdsahkdjska
                  type: string
              required:
                - user-name
                - user-password
                - user-email
                - user-nickname
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                required:
                  - success_message
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 用户注册成功，请查收邮件激活账号
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 管理员密钥错误
                '2':
                  summary: 异常示例
                  value:
                    error_message: 用户注册参数不足
                '3':
                  summary: 异常示例
                  value:
                    error_message: 用户名长度不合法
                '4':
                  summary: 异常示例
                  value:
                    error_message: 用户名只能包含字母和数字
                '5':
                  summary: 异常示例
                  value:
                    error_message: 密码长度不合法
                '6':
                  summary: 异常示例
                  value:
                    error_message: 邮箱格式不合法
                '7':
                  summary: 异常示例
                  value:
                    error_message: 昵称长度不合法
                '8':
                  summary: 异常示例
                  value:
                    error_message: 用户名已存在
                '9':
                  summary: 异常示例
                  value:
                    error_message: 邮箱已存在
        '403':
          description: 禁止访问
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息，用中文表示
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 邮件发送过于频繁，请等待五分钟再试
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  errpr_message:
                    type: string
                    title: 错误信息
                    description: 错误信息，用中文表示
                required:
                  - errpr_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    errpr_message: 用户注册失败
                '2':
                  summary: 异常示例
                  value:
                    errpr_message: 密码加密失败
                '3':
                  summary: 异常示例
                  value:
                    errpr_message: 用户邮箱注册失败
                '4':
                  summary: 异常示例
                  value:
                    errpr_message: 邮件发送失败
                '5':
                  summary: 异常示例
                  value:
                    errpr_message: 查询用户邮箱失败
                '6':
                  summary: 异常示例
                  value:
                    errpr_message: 不存在当前邮箱
                '7':
                  summary: 异常示例
                  value:
                    errpr_message: 更新用户邮箱失败
                '8':
                  summary: 异常示例
                  value:
                    errpr_message: CSRF Token 获取失败
      security: []
  /csrf-token:
    get:
      summary: 获取csrf token
      deprecated: false
      description: 用于一开始获取csrf token
      tags:
        - Security
      parameters: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  在响应头里找到X-CSRF-Token:
                    type: string
                required:
                  - 在响应头里找到X-CSRF-Token
      security: []
  /users/records-all:
    get:
      summary: 获取所有用户使用记录
      deprecated: false
      description: 通过用户ID获取该用户的所有使用记录
      tags:
        - Record
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          example: Bearer sdsadsadsadasdsa
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                  records:
                    allOf:
                      - &ref_0
                        $ref: '#/components/schemas/RecordInfo'
                      - *ref_0
                      - *ref_0
                required:
                  - success_message
                  - records
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 获取全部诊断信息成功
                    records:
                      '0':
                        RecordId: 220000197602187680
                        Date: '2013-01-30 20:33:32'
                        Result: http://jamvmwxtd.tk/baj
                        PatientName: Nancy Robinson
        '401':
          description: 没有权限
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 验证令牌过期或错误
      security: []
  /users/records/{recordsid}:
    get:
      summary: 获取用户使用记录
      deprecated: false
      description: 通过使用记录ID获取用户使用记录
      tags:
        - Record
      parameters:
        - name: recordsid
          in: path
          description: 使用记录id
          required: true
          example: '1'
          schema:
            type: integer
        - name: Authorization
          in: header
          description: 登录令牌
          required: true
          example: Bearer sdsuahdskhadkahsdui
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                  RecordId:
                    type: integer
                    description: 每个记录对应的id
                    title: 记录id
                  Date:
                    type: string
                    title: 检测时间
                    description: 检测时间
                  Result:
                    type: string
                    title: 结果
                    description: 可能是图片或者视频的链接
                  PatientName:
                    type: string
                    title: 患者姓名
                    description: 患者姓名
                required:
                  - success_message
                  - RecordId
                  - Date
                  - Result
                  - PatientName
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 获取对应记录成功
                    RecordId: 140000201710096930
                    Date: '1970-12-31 13:48:41'
                    Result: http://prtvzvad.sr/wfcbi
                    PatientName: Paul Lee
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 参数错误
        '401':
          description: 没有权限
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 登录令牌错误或过期
      security: []
  /users/login:
    post:
      summary: 用户登录
      deprecated: false
      description: 用户通过用户名和密码登录
      tags:
        - User
      parameters:
        - name: X-Csrf-Token
          in: header
          description: ''
          required: true
          example: "\tmrsnYbPWKFStwPegqplYxGQByPxybJkf"
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                user-name:
                  description: 用户名
                  example: orange
                  type: string
                user-password:
                  description: 用户密码
                  example: bsbflsgxh..
                  type: string
              required:
                - user-name
                - user-password
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    title: 验证令牌
                    description: 验证令牌
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                required:
                  - success_message
                  - token
              examples:
                '1':
                  summary: 成功示例
                  value:
                    token: plQtBl
                    success_message: 登录成功
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 密码错误
                '2':
                  summary: 异常示例
                  value:
                    error_message: 用户名或密码为空
        '404':
          description: 记录不存在
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息，用中文表示
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 用户不存在
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息，用中文表示
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 查询用户失败
                '2':
                  summary: 异常示例
                  value:
                    error_message: 生成Token失败*
                '3':
                  summary: 异常示例
                  value:
                    error_message: CSRF Token 获取失败
      security: []
  /detection:
    post:
      summary: 进行检测
      deprecated: false
      description: 上传图片进行检测
      tags:
        - Feature
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          example: Bearer sdhkahdjkshadjkhsakjdhkas
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  format: binary
                  type: string
                  description: 图片
              required:
                - image
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                required:
                  - success_message
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 检测成功，请前往记录查看结果
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 图片参数错误
        '401':
          description: 没有权限
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 令牌过期或错误
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 服务器运行bug，请联系管理员
      security: []
  /segmentation:
    post:
      summary: 进行分割
      deprecated: false
      description: 上传图片进行分割
      tags:
        - Feature
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          example: Bearer sdhkahdjkshadjkhsakjdhkas
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  format: binary
                  type: string
                  description: 图片
              required:
                - image
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                required:
                  - success_message
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 分割成功，请前往记录查看结果
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 图片参数错误
        '401':
          description: 没有权限
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 令牌过期或错误
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 服务器运行bug，请联系管理员
      security: []
  /track:
    post:
      summary: 进行追踪
      deprecated: false
      description: 上传视频进行追踪
      tags:
        - Feature
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          example: Bearer sdhkahdjkshadjkhsakjdhkas
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  format: binary
                  type: string
                  description: 视频
              required:
                - video
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                required:
                  - success_message
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 追踪成功，请前往记录查看结果
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 视频参数错误
        '401':
          description: 没有权限
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 令牌过期或错误
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 服务器运行bug，请联系管理员
      security: []
  /users/account/activation/{token}:
    put:
      summary: 激活用户账户
      deprecated: false
      description: 通过激活码激活用户账户
      tags:
        - User
      parameters:
        - name: token
          in: path
          description: 激活验证的唯一标识符
          required: true
          example: ashdjkshajdhjksahdkjas
          schema:
            type: string
        - name: X-Csrf-Token
          in: header
          description: CSRF
          required: true
          example: shkdhkahwdkhwa
          schema:
            type: string
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                required:
                  - success_message
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 用户激活成功
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 激活码不存在
                '2':
                  summary: 异常示例
                  value:
                    error_message: 用户已激活
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息，用中文表示
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 数据库查询失败
                '2':
                  summary: 异常示例
                  value:
                    error_message: 数据库更新失败
                '3':
                  summary: 异常示例
                  value:
                    error_message: CSRF Token 获取失败
      security: []
  /users/account/nickname:
    put:
      summary: 修改用户昵称
      deprecated: false
      description: 通过用户ID修改用户昵称，用户id从认证码中解析，无需传递
      tags:
        - User
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          example: Bearer sdhjksahdkash
          schema:
            type: string
        - name: X-Csrf-Token
          in: header
          description: CSRF
          required: true
          example: ksjahdiwahdksah
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                user-nickname:
                  description: 需要更改的值
                  example: 晋晨曦
                  type: string
              required:
                - user-nickname
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                required:
                  - success_message
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 更新用户昵称成功
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 昵称不能为空
                '2':
                  summary: 异常示例
                  value:
                    error_message: 昵称长度不符合要求
        '404':
          description: 记录不存在
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息，用中文表示
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 用户不存在
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息，用中文表示
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 获取用户信息失败
                '2':
                  summary: 异常示例
                  value:
                    error_message: 更新用户昵称失败
      security: []
  /users/account/password:
    put:
      summary: 修改用户密码
      deprecated: false
      description: |-
        通过用户ID修改用户昵称，用户id从认证码中解析，无需传递
        你需要在前端做一些常规判断，例如让用户输入两次密码等等。
      tags:
        - User
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          example: Bearer sdhjksahdkash
          schema:
            type: string
        - name: X-Csrf-Token
          in: header
          description: CSRF令牌
          required: true
          example: sahkdiwhadush
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                user-password:
                  description: 需要更改的值
                  example: safsfsadsa
                  type: string
              required:
                - user-password
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                required:
                  - success_message
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 修改密码成功
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 密码不能为空
                '2':
                  summary: 异常示例
                  value:
                    error_message: 密码长度不符合要求
                '3':
                  summary: 异常示例
                  value:
                    error_message: 新密码与旧密码相同
        '404':
          description: 记录不存在
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 用户不存在
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息，用中文表示
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 获取用户信息失败
                '2':
                  summary: 异常示例
                  value:
                    error_message: 密码加密失败
                '3':
                  summary: 异常示例
                  value:
                    error_message: 更新用户信息失败
      security: []
  /users/records/{recordid}:
    delete:
      summary: 删除使用记录
      deprecated: false
      description: 通过用户ID和使用记录ID删除用户使用记录
      tags:
        - Record
      parameters:
        - name: recordid
          in: path
          description: 记录id
          required: true
          example: '12'
          schema:
            type: integer
        - name: Authorization
          in: header
          description: 令牌
          required: true
          example: Bearer adsdhjkshadjkhaskjd
          schema:
            type: string
      responses:
        '204':
          description: 删除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
                    title: 成功信息
                    description: 成功信息
                required:
                  - success_message
              examples:
                '1':
                  summary: 成功示例
                  value:
                    success_message: 删除成功
        '400':
          description: 请求有误
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 记录id与用户id不匹配
                '2':
                  summary: 异常示例
                  value:
                    error_message: 记录id不存在
        '401':
          description: 没有权限
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  error_message:
                    type: string
                    title: 错误信息
                    description: 错误信息
                required:
                  - error_message
              examples:
                '1':
                  summary: 异常示例
                  value:
                    error_message: 身份令牌过期或错误
      security: []
components:
  schemas:
    RecordInfo:
      type: object
      properties:
        RecordId:
          type: integer
          description: 每个记录对应的id
          title: 记录id
        Date:
          type: string
          title: 检测时间
          description: 检测时间
        Result:
          type: string
          title: 结果
          description: 可能是图片或者视频的链接
        PatientName:
          type: string
          title: 患者姓名
          description: 患者姓名
      required:
        - RecordId
        - Date
        - Result
        - PatientName
    UserInfo:
      type: object
      properties:
        UserName:
          type: string
          title: 用户名
          description: 唯一的用户名，类似于账号
        UserEmail:
          type: string
          title: 用户邮箱
          description: 用户邮箱，用于验证注册
        UserNickName:
          type: string
          title: 用户昵称
          description: 一个随意好听的名字
        UserIsAdmin:
          type: boolean
          title: 是否是管理员
          description: 是否是管理员
      required:
        - UserName
        - UserEmail
        - UserNickName
        - UserIsAdmin
  securitySchemes: {}
servers: []
